environment:
  nodejs_version: "6"
  
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm i electron -g
  
test_script:
  - node --version
  - npm --version
  - npm test
